### ISSUE TITLE
using label_percentage in plot_dependencies produces blank nodes

### ISSUE THREAD

**Issue by hbaniecki** [DominikRafacz/deepdep#12]
```
#:# This produces not informative message (could be catched sooner)
plot_dependencies("deepdep", label_percentage = 0.5)

#:# This shows blank package nodes and arrows
plot_dependencies("deepdep", show_downloads = TRUE, label_percentage = 0.5)
```

**Comment by MatiFilozof** [comment]
Fixed both problems; now
`plot_dependencies("deepdep", label_percentage = 0.5)`
executes properly without throwing an exception and
`plot_dependencies("deepdep", show_downloads = TRUE, label_percentage = 0.5)`
shows small dots whenever package has not enough downloads to be plotted with label (instead of empty labels, as previously).
