### ISSUE TITLE
`plot_dependencies()` doesn't work with the latest `{igraph}` 

### ISSUE THREAD

**Issue by IndrajeetPatil** [DominikRafacz/deepdep#51]
Looks like `{igraph}` update on CRAN has broken `{deepdep}`:

https://cran.rstudio.com/web/checks/check_results_deepdep.html

**Comment by szhorvat** [comment]
This is due to the intentional breaking change noted in igraph's NEWS file:

https://cran.r-project.org/web/packages/igraph/news/news.html

When setting vertex or edge attributes, the number of values supplied must now exactly match the number of vertices or edges. 

Previously, recycling was used to fill out the missing elements.

**Comment by ErdaradunGaztea** [comment]
Ooops! Thanks for the details, sounds like we have some bad coding practices on our hands.

**Comment by DominikRafacz** [comment]
This issue is closed in 0.4.2 version. It has already been submitted to CRAN, should be published soon
